### ISSUE TITLE
RSS Feed does not validate

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#4076]
Ampache 7.0.1

RSS feed from the home page does not valide if we take a look at https://www.rssboard.org/rss-validator/

Some bug are easy to fix : 
Missing channel element: description
```diff
+        <description tal:content="TITLE">TITLE</description>
```

comments must be a full and valid URL:
```diff
-            <comments tal:content="item/comments">COMMENTS</comments>
+           <comments tal:condition="item/comments | false" tal:content="item/comments">COMMENTS</comments>
```

pubDate must be an RFC-822 date-time: 
```diff
-            <pubDate tal:content="item/pubDate">PUBDATE</pubDate>
+           <pubDate tal:condition="item/pubDate | false" tal:content="item/pubDate">PUBDATE</pubDate>
```

But : 
- it would be great to give real datetime (for example, real date for `/rss.php?type=latest_artist` would be useful). But class does not implement method to get those, and I'm not sure we even have this info
- image element does not exist in items, and I don't know if it's an ampache feature or an error. If it's an error, the real method would be to use https://cyber.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt but I don't see how to implement this properly (I can do ugly working patch... but that is not the way).

**Comment by fufroma** [comment]
Ampache 7.2.0 
`(log.lib) -> [Runtime Error] Undefined array key "SCRIPT_URI" in file src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php(112)`

SCRIPT_URI does not exist all the time

Bug was introduced in https://github.com/ampache/ampache/commit/a32f056743fb3add6d0593e5963061bfe228bb77

dirty fix
``` diff
$ git diff src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php
diff --git a/src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php b/src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php
index 55aa6df44..a513a96bf 100644
--- a/src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php
+++ b/src/Module/Util/Rss/Surrogate/PlayableItemRssItemAdapter.php
@@ -109,7 +109,7 @@ final readonly class PlayableItemRssItemAdapter implements RssItemInterface
      */
     public function getRssLink(): string
     {
-        return $_SERVER['SCRIPT_URI'] . '?' . $_SERVER['QUERY_STRING'];
+        return $_SERVER['SCRIPT_URI']??'/rss.php' . '?' . $_SERVER['QUERY_STRING'];
     }
 
     /**


```

**Comment by lachlan-00** [comment]
9ee4a48207cf2c5184cb3ebcf1d2fc4fd0704ce5 sets a fallback on uri

**Comment by fufroma** [comment]
@lachlan-00 do you have any insight about this:
> image element does not exist in items, and I don't know if it's an ampache feature or an error. If it's an error, the real method would be to use https://cyber.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt but I don't see how to implement this properly (I can do ugly working patch... but that is not the way).

Should we fix it or should we keep it that way becayse it's used by some other tools

**Comment by lachlan-00** [comment]
i don't fully follow this one. does it need an <image> for the feed or per item?

I also looked at some of the feed links and album feed doesn't validate still

**Comment by fufroma** [comment]
We can do as we want: one per item or one per feed. But anyway, we need to fix the way we integrate the img to allow reader to display it

**Comment by lachlan-00** [comment]
i think i've got this enclosure sorted. just testing

**Comment by lachlan-00** [comment]
we do actually have one issue, image is meant to be used by the feed not the item.

then the other issue is size of the thumb is going to be hard to get. i'll see if i've got any code for that somewhere. it may be cached

but for the momenti'm going to remove image from the item and put it in the feed if it exists

**Comment by lachlan-00** [comment]
done with 66ea32661013c1547dd8c8a7efa00c7005515197

and 41565242152f614b6f1fb776cf99da7b22dbef46 when nothing is playing

I'll try and look at whether size is cached ant then i can add that as an enclosure in items individually

**Comment by lachlan-00** [comment]
valid date format and image element added with 74d666f619fffb848d5505b921d3217c9325d73c

validator rates now_playing as valid

**Comment by fufroma** [comment]
fix for date in latest_shout

```diff
$ git diff src/Module/Util/Rss/Type/LatestShoutFeed.php
diff --git a/src/Module/Util/Rss/Type/LatestShoutFeed.php b/src/Module/Util/Rss/Type/LatestShoutFeed.php
index f5d66f2c3..7ca1e1166 100644
--- a/src/Module/Util/Rss/Type/LatestShoutFeed.php
+++ b/src/Module/Util/Rss/Type/LatestShoutFeed.php
@@ -66,7 +66,7 @@ final readonly class LatestShoutFeed extends AbstractGenericRssFeed
                     'link' => $object->get_link(),
                     'description' => $shout->getText(),
                     'comments' => '',
-                    'pubDate' => $shout->getDate()->format(DATE_ATOM),
+                    'pubDate' => $shout->getDate()->format(DATE_RFC2822),
                     'guid' => 'shout-' . $shout->getId(),
                     'isPermaLink' => 'false',
                     'image' => (string) Art::url($shout->getObjectId(), $shout->getObjectType()->value, null, 2),

```

**Comment by fufroma** [comment]
fix for date in latest_album
```diff
$ git diff src/Module/Util/Rss/Type/LatestAlbumFeed.php
diff --git a/src/Module/Util/Rss/Type/LatestAlbumFeed.php b/src/Module/Util/Rss/Type/LatestAlbumFeed.php
index f16400904..354c12882 100644
--- a/src/Module/Util/Rss/Type/LatestAlbumFeed.php
+++ b/src/Module/Util/Rss/Type/LatestAlbumFeed.php
@@ -63,7 +63,7 @@ final readonly class LatestAlbumFeed extends AbstractGenericRssFeed
                 'link' => $album->get_link(),
                 'description' => $album->get_artist_fullname() . ' - ' . $album->get_fullname(true),
                 'comments' => '',
-                'pubDate' => date("c", $album->addition_time),
+                'pubDate' => date(DATE_RFC2822, $album->addition_time),
                 'guid' => (isset($album->mbid)) ? 'https://musicbrainz.org/release/' . $album->mbid : (isset($album->mbid_group) ? 'https://musicbrainz.org/release-group/' . $album->mbid_group : 'album-' . $album->id),
                 'isPermaLink' => (isset($album->mbid) || isset($album->mbid_group))
                     ? 'true'

```

**Comment by fufroma** [comment]
fixed in next release
